### ISSUE TITLE
Very similar to Query Engine

### ISSUE THREAD

**Issue by balupton** [logicalparadox/filtr#2]
Hey dude,

Nice work on this. Not sure if you know, but I have a very similar project called [Query Engine](https://github.com/bevry/query-engine) which seems to do the same stuff.

What are your thoughts, should we join forces?

**Comment by logicalparadox** [comment]
Query Engine looks good. Certainly more mongo compliant at the moment.

Given my use of `filtr` within some of my other modules, namely seed, this project isn't going anywhere soon. I am open to any thoughts if you have them.

One difference I noticed was that QueryEngine has production deps of underscore and backbone while `filtr` is dep free. Just an observation.

**Comment by drauschenbach** [comment]
Query Engine is pretty heavy, and hard to debug with its blending of isomorphic compilation, CoffeeScript, and Backbone.

A lightweight library like `filtr` still has a place.
